version: "3"
services:
  data-structure-algorithm.nginx:
    build: ./data-structure-algorithm.nginx
    container_name: data-structure-algorithm.nginx
    env_file:
      - .env
    ports:
      - 81:80
    depends_on:
      - data-structure-algorithm.web

  data-structure-algorithm.web:
    build: ./data-structure-algorithm.web
    container_name: data-structure-algorithm.web
    env_file:
      - .env
    expose:
      - ${WEB_PORT}

    # depends_on:
    #   - data-structure-algorithm.db

  # data-structure-algorithm.db:
  #   container_name: data-structure-algorithm.db
  #   image: mongo
  #   restart: always
  #   env_file:
  #     - .env
  #   expose:
  #     - ${DB_PORT}
  #   volumes:
  #     - ./data-structure-algorithm.db:/data/db
  #     - ./data-structure-algorithm.db:/data/configdb

  # data-structure-algorithm.db.admin:
  #   container_name: data-structure-algorithm.db.admin
  #   image: mongo-express
  #   restart: always
  #   expose:
  #     - ${DB_ADMIN_PORT}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - data-structure-algorithm.db